backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "data/projects"  # For individual files
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Partner", name: "partner", widget: "string"}
      - label: "Gallery Images"
        name: "gallery"
        widget: "list"
        field: {label: "Image", name: "image", widget: "image"}