backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    file: "data/projects.json"  # Single file instead of folder
    fields:
      - { name: "title", label: "Title" }
      - { name: "description", label: "Description", widget: "markdown" }
      - { name: "partner", label: "Partner" }
      - label: "Gallery Images"
        name: "gallery"
        widget: "list"
        field: { name: "image", label: "Image", widget: "image" }