backend:
  name: git-gateway
  branch: main  # Your GitHub branch

# Media folder (for image uploads)
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "data/products"  # Stores product JSON files
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "scientific_name", label: "Scientific Name", widget: "string" }
      - { name: "description", label: "Description", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "projects"
    label: "Projects"
    folder: "data/projects"  # Stores project JSON files
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "markdown" }
      - { name: "images", label: "Gallery", widget: "list", field: { name: "image", label: "Image", widget: "image" } }
